In [40]:
# 数据读取
import pandas as pd
import os
pd.set_option('display.max_columns', None)
data1 = pd.read_csv("data1.csv", encoding="utf-8")

C:\Users\Administrator\AppData\Local\Temp\ipykernel_25560\3666823645.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data1 = pd.read_csv("data1.csv", encoding="utf-8")

In [33]:
data1

,流水号,校园卡号,校园卡编号,消费时间,消费金额,存储金额,余额,消费次数,消费类型,消费项目编码,消费项目序列号,消费操作编码,操作编码,消费地点,消费时间_F,消费时间_5,Date_5_cnt,性别,tsm
0,116925030,180641-女,2018641,2019-04-01 10:00:00,3.5,0.0,206.70,804,消费,107,NaN,NaN,135,红太阳超市,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
1,116969953,181021-女,20181021,2019-04-01 10:00:00,2.0,0.0,127.90,512,消费,12,NaN,NaN,236,第一食堂,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
2,116969952,181036-女,20181036,2019-04-01 10:00:00,3.0,0.0,12.60,451,消费,12,NaN,NaN,236,第一食堂,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
3,116967877,181049-女,20181049,2019-04-01 10:00:00,7.0,0.0,47.80,585,消费,172,NaN,NaN,230,第四食堂,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
4,116925031,180691-女,2018691,2019-04-01 10:00:00,2.0,0.0,109.26,935,消费,107,NaN,NaN,135,红太阳超市,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241074,117094829,180008-男,20188,2019-04-09 09:58:00,6.2,0.0,16.80,525,消费,114,NaN,NaN,8,第五食堂,2019-04-09 09:58:00,2019-04-09 09_12,10,男,2019040909(11);2019040910(00)
241075,117083410,180826-女,2018826,2019-04-09 09:58:00,15.1,0.0,66.40,350,消费,107,NaN,NaN,2,红太阳超市,2019-04-09 09:58:00,2019-04-09 09_12,10,女,2019040909(11);2019040910(00)
241076,117081746,182748-男,20182748,2019-04-09 09:59:00,13.0,0.0,87.40,358,消费,196,NaN,NaN,133,好利来食品店,2019-04-09 09:59:00,2019-04-09 09_12,10,男,2019040909(11);2019040910(00)
241077,117107493,181202-女,20181202,2019-04-09 09:59:00,3.0,0.0,161.80,797,消费,88,NaN,NaN,233,第二食堂,2019-04-09 09:59:00,2019-04-09 09_12,10,女,2019040909(11);2019040910(00)
241078,117079225,181891-男,20181891,2019-04-09 09:59:00,0.0,80.0,81.40,473,存款,202,NaN,NaN,201,财务处,2019-04-09 09:59:00,2019-04-09 09_12,10,男,2019040909(11);2019040910(00)

In [17]:
import datetime
'''
函数功能
时间格式调整
'2019/4/20 20:17'=>'2019-04-20 20:17:00'
'''
def st_pt(x):
     return str(datetime.datetime.strptime(x, "%Y/%m/%d %H:%M"))
'''
函数功能
时间切片
5分钟一个切片，且每个时间会切成两个片段
Time2Str('2021-11-16 15:51:39' )
'2021-11-16 15:51:39'  => '2021111615(10);2021111615(11)'
'''
def Time2Str(tsm):
    t0 = datetime.datetime.fromisoformat(tsm)
    t1 = t0+datetime.timedelta(days=0, hours=5/60)
    str1 = t0.strftime("%Y%m%d%H")+'(' +str(round(int(t0.minute/5))).rjust(2,'0')+')'
    str2 = t1.strftime("%Y%m%d%H")+'(' +str(round(int(t1.minute/5))).rjust(2,'0')+')'
    return str1+';'+str2

In [41]:
# 开始数据处理
df = data1
df['消费时间'] = df['消费时间'].apply(st_pt)
df['tsm']     = df['消费时间'].apply(Time2Str)

In [42]:
df

,流水号,校园卡号,校园卡编号,消费时间,消费金额,存储金额,余额,消费次数,消费类型,消费项目编码,消费项目序列号,消费操作编码,操作编码,消费地点,消费时间_F,消费时间_5,Date_5_cnt,性别,tsm
0,116925030,180641-女,2018641,2019-04-01 10:00:00,3.5,0.0,206.70,804,消费,107,NaN,NaN,135,红太阳超市,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
1,116969953,181021-女,20181021,2019-04-01 10:00:00,2.0,0.0,127.90,512,消费,12,NaN,NaN,236,第一食堂,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
2,116969952,181036-女,20181036,2019-04-01 10:00:00,3.0,0.0,12.60,451,消费,12,NaN,NaN,236,第一食堂,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
3,116967877,181049-女,20181049,2019-04-01 10:00:00,7.0,0.0,47.80,585,消费,172,NaN,NaN,230,第四食堂,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
4,116925031,180691-女,2018691,2019-04-01 10:00:00,2.0,0.0,109.26,935,消费,107,NaN,NaN,135,红太阳超市,2019-04-01 10:00:00,2019-04-01 10_0,38,女,2019040110(00);2019040110(01)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241074,117094829,180008-男,20188,2019-04-09 09:58:00,6.2,0.0,16.80,525,消费,114,NaN,NaN,8,第五食堂,2019-04-09 09:58:00,2019-04-09 09_12,10,男,2019040909(11);2019040910(00)
241075,117083410,180826-女,2018826,2019-04-09 09:58:00,15.1,0.0,66.40,350,消费,107,NaN,NaN,2,红太阳超市,2019-04-09 09:58:00,2019-04-09 09_12,10,女,2019040909(11);2019040910(00)
241076,117081746,182748-男,20182748,2019-04-09 09:59:00,13.0,0.0,87.40,358,消费,196,NaN,NaN,133,好利来食品店,2019-04-09 09:59:00,2019-04-09 09_12,10,男,2019040909(11);2019040910(00)
241077,117107493,181202-女,20181202,2019-04-09 09:59:00,3.0,0.0,161.80,797,消费,88,NaN,NaN,233,第二食堂,2019-04-09 09:59:00,2019-04-09 09_12,10,女,2019040909(11);2019040910(00)
241078,117079225,181891-男,20181891,2019-04-09 09:59:00,0.0,80.0,81.40,473,存款,202,NaN,NaN,201,财务处,2019-04-09 09:59:00,2019-04-09 09_12,10,男,2019040909(11);2019040910(00)

In [43]:
df = df.set_index(["校园卡号", "消费时间",'消费地点'])["tsm"].str.split(";", expand=True)\
    .stack().reset_index(drop=True, level=-1).reset_index().rename(columns={0: "tsm"})
print(df)

            校园卡号                 消费时间    消费地点             tsm
0       180641-女  2019-04-01 10:00:00   红太阳超市  2019040110(00)
1       180641-女  2019-04-01 10:00:00   红太阳超市  2019040110(01)
2       181021-女  2019-04-01 10:00:00    第一食堂  2019040110(00)
3       181021-女  2019-04-01 10:00:00    第一食堂  2019040110(01)
4       181036-女  2019-04-01 10:00:00    第一食堂  2019040110(00)
...          ...                  ...     ...             ...
482153  182748-男  2019-04-09 09:59:00  好利来食品店  2019040910(00)
482154  181202-女  2019-04-09 09:59:00    第二食堂  2019040909(11)
482155  181202-女  2019-04-09 09:59:00    第二食堂  2019040910(00)
482156  181891-男  2019-04-09 09:59:00     财务处  2019040909(11)
482157  181891-男  2019-04-09 09:59:00     财务处  2019040910(00)

[482158 rows x 4 columns]

In [44]:

# 数据匹配，加入时间约束和地点约束
df_0 = pd.merge(df,df,on =['tsm','消费地点'],how='inner')
df_0.shape

(46298620, 6)

In [45]:
# 排除 自己和自己匹配的数据
df_1 = df_0[df_0['校园卡号_x']!=df_0['校园卡号_y']]

In [46]:
# 时间作差，大于5分钟的排除
df_1['diff'] = (pd.to_datetime(df_1['消费时间_x'])-pd.to_datetime(df_1['消费时间_y'])).dt.seconds/60
df_1 = df_1[df_1['diff']<=5]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_25560\4137133835.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['diff'] = (pd.to_datetime(df_1['消费时间_x'])-pd.to_datetime(df_1['消费时间_y'])).dt.seconds/60

In [48]:
df_1

,校园卡号_x,消费时间_x,消费地点,tsm,校园卡号_y,消费时间_y,diff,date
1,180641-女,2019-04-01 10:00:00,红太阳超市,2019040110(00),180691-女,2019-04-01 10:00:00,0.0,2019040110
2,180641-女,2019-04-01 10:00:00,红太阳超市,2019040110(00),181015-女,2019-04-01 09:55:00,5.0,2019040110
3,180641-女,2019-04-01 10:00:00,红太阳超市,2019040110(00),180662-女,2019-04-01 09:55:00,5.0,2019040110
4,180641-女,2019-04-01 10:00:00,红太阳超市,2019040110(00),181019-女,2019-04-01 09:55:00,5.0,2019040110
5,180641-女,2019-04-01 10:00:00,红太阳超市,2019040110(00),184062-女,2019-04-01 09:56:00,4.0,2019040110
...,...,...,...,...,...,...,...,...
46298610,182991-男,2019-04-09 09:57:00,好利来食品店,2019040910(00),183942-男,2019-04-09 09:57:00,0.0,2019040910
46298613,182748-男,2019-04-09 09:59:00,好利来食品店,2019040910(00),182991-男,2019-04-09 09:56:00,3.0,2019040910
46298614,182748-男,2019-04-09 09:59:00,好利来食品店,2019040910(00),183020-男,2019-04-09 09:56:00,3.0,2019040910
46298615,182748-男,2019-04-09 09:59:00,好利来食品店,2019040910(00),183942-男,2019-04-09 09:57:00,2.0,2019040910
46298616,182748-男,2019-04-09 09:59:00,好利来食品店,2019040910(00),182991-男,2019-04-09 09:57:00,2.0,2019040910

In [47]:
# 提取小时 按共同出现的小时计数
df_1['date'] = df_1['tsm'].apply(lambda x :x[0:10])

In [69]:
#统计两两关联的次数，这里比较简单，不按天，也不计算相似度了
df_2 = df_1.groupby(['校园卡号_x','校园卡号_y']).agg({'date': pd.Series.nunique}).reset_index()

In [68]:
df_2['校园卡号_x']='183847-女'

In [67]:
df_2 [df_2['校园卡号_x']='183847-女']

SyntaxError: invalid syntax (313330896.py, line 1)

In [51]:
# 降序排列
df_2 = df_2.sort_values(by='date',ascending=False)

In [52]:
df_3 = df_2[df_2['date']>=20]

In [53]:
df_3

           校园卡号_x    校园卡号_y  date
1031801  181293-女  181268-女    68
1008844  181268-女  181293-女    64
343421   180399-女  183665-女    60
309673   180363-女  181876-女    58
1967448  182392-女  182377-女    58
...           ...       ...   ...
156386   180173-女  180109-女    20
271647   180320-女  183546-女    20
2884196  183692-女  180377-女    20
66844    180085-女  180394-女    20
1801477  182194-女  182212-女    20

[1924 rows x 3 columns]

In [54]:
import matplotlib.pyplot as plt
import networkx as nx
from networkx.algorithms.community import asyn_lpa_communities as lpa

In [70]:
import community

In [72]:
G = nx.Graph()
G.add_edges_from(tuples)
partition = community.best_partition(G)

In [77]:
community.modularity(partition,G)

0.9801008108700513

In [101]:
partition['181103-男']

25

In [80]:
com

[{'181268-女', '181293-女'},
 {'180399-女', '183665-女'},
 {'180363-女', '180364-女', '181876-女', '183979-女'},
 {'180111-女',
  '180167-女',
  '182049-女',
  '182138-女',
  '182180-女',
  '182213-女',
  '182350-女',
  '182377-女',
  '182392-女',
  '182622-女',
  '184188-女',
  '184238-女'},
 {'183419-女', '183420-女', '183422-女', '183424-女'},
 {'180726-女', '180742-女'},
 {'180792-女', '180822-女', '180849-女'},
 {'181928-女', '181929-女', '181951-女'},
 {'181184-女', '181201-女', '181203-女'},
 {'180714-女', '180728-女', '180747-女', '181263-女'},
 {'181848-女', '181865-女', '181871-女'},
 {'183579-女', '183582-女', '183603-女'},
 {'180091-女', '180094-女', '180131-女', '180203-女', '180208-女'},
 {'181338-男', '181343-男', '181344-男', '181350-男'},
 {'182278-女', '182300-女'},
 {'181273-女', '181316-女', '181318-女'},
 {'180085-女',
  '180171-女',
  '180189-女',
  '180342-男',
  '180360-女',
  '180377-女',
  '180382-女',
  '180394-女',
  '180412-女'},
 {'182976-男', '182978-男', '182980-男', '183009-男'},
 {'182865-男', '183097-男', '184277-男'},
 {'182196-女', '182200-女', '182201-女', '182210-女'},
 {'183243-女', '183260-女'},
 {'183641-女', '183688-女', '183690-女'},
 {'180545-女', '180547-女', '180578-女', '180615-女'},
 {'182320-女', '182332-女', '182378-女', '184179-女', '184184-女'},
 {'181650-男', '181661-男', '184104-男'},
 {'181379-男', '181381-男', '181383-男', '181448-男'},
 {'180783-女', '180793-女', '184028-女'},
 {'180711-女', '180712-女', '180732-女', '180738-女'},
 {'180102-女', '180113-女', '180169-女', '180173-女', '180193-女', '182345-女'},
 {'183644-女', '183647-女'},
 {'180383-女', '183343-男', '183980-女'},
 {'181066-男', '181069-男', '181073-男', '181091-男', '181103-男'},
 {'180551-女', '180587-女', '180593-女', '180609-女', '180614-女'},
 {'181133-男', '181136-男', '181552-男', '181571-男', '181582-男'},
 {'182239-男', '182304-女', '182329-女', '182340-女', '182403-女'},
 {'183768-男', '183772-男', '184333-男'},
 {'181656-男', '181658-男', '181664-男'},
 {'183671-女',
  '183701-女',
  '183713-女',
  '183719-女',
  '183726-女',
  '183732-女',
  '183734-女',
  '183737-女',
  '183742-女',
  '183850-女',
  '183851-女',
  '183853-女',
  '183881-女'},
 {'181556-男', '181559-男', '181564-男', '181568-男'},
 {'181191-女', '182333-女'},
 {'183303-女', '183307-女', '183314-女'},
 {'181498-男', '181505-男', '181506-男', '181536-男', '181543-男'},
 {'180136-女', '180137-女', '180159-女', '180165-女', '180197-女'},
 {'180448-女',
  '180467-女',
  '180477-女',
  '180486-女',
  '180504-女',
  '180505-女',
  '180506-女'},
 {'180800-女', '184024-女', '184034-女', '184036-女'},
 {'182807-女', '182810-女', '182813-女', '182819-女', '182821-女'},
 {'182551-女', '182555-女', '182565-女'},
 {'180122-女', '180133-女'},
 {'180780-女', '180851-女', '180856-女', '181461-男'},
 {'182459-女', '182474-女'},
 {'180457-女', '180459-女', '180493-女', '180500-女', '181176-女'},
 {'182361-女', '184190-女'},
 {'182866-男', '182878-男'},
 {'180644-女', '180666-女', '180672-女', '180690-女'},
 {'182427-女', '182475-女', '182517-女'},
 {'180445-女', '180464-女', '180466-女', '180482-女', '180511-女', '181847-女'},
 {'180087-女', '180095-女', '180098-女', '180144-女', '180202-女'},
 {'180651-女', '180665-女', '183999-女'},
 {'181408-男', '181443-男'},
 {'182677-女', '182703-女', '182705-女'},
 {'181921-女', '181943-女', '181952-女'},
 {'180683-女', '180694-女', '183997-女'},
 {'183709-女',
  '183712-女',
  '183739-女',
  '183753-女',
  '183852-女',
  '183854-女',
  '183859-女',
  '183872-女'},
 {'182115-女', '182120-女', '182130-女', '182205-女'},
 {'181142-男', '184098-男', '184100-男'},
 {'183787-女', '183798-女'},
 {'183074-男', '183107-男', '183123-男', '184298-男'},
 {'182758-男', '182759-男', '182764-男', '182783-男', '182788-男'},
 {'180026-女', '180048-女', '180055-女', '183901-女'},
 {'183202-男', '183234-男'},
 {'181325-男', '181346-男', '181355-男'},
 {'180293-女', '180309-女', '180328-女'},
 {'180704-男', '180705-男'},
 {'181500-男', '181503-男', '181507-男', '181508-男', '181509-男', '181530-男'},
 {'181515-男', '181534-男'},
 {'181016-女', '181026-女', '181034-女'},
 {'183640-女', '183642-女'},
 {'181597-男', '181623-男', '181626-男', '183847-女'},
 {'182983-男', '182986-男', '182987-男', '182999-男'},
 {'183330-男', '183338-男', '183341-男', '183344-男', '183345-男'},
 {'183569-女', '183583-女', '183599-女'},
 {'180262-女', '180820-女'},
 {'183468-女', '183469-女', '183488-女'},
 {'180252-女', '180316-女', '183952-女'},
 {'183661-女', '183675-女', '183711-女', '183743-女'},
 {'180105-女', '180118-女', '180164-女', '180198-女'},
 {'183385-女', '183401-女'},
 {'181364-男', '181528-男', '181529-男'},
 {'182016-男', '182029-男', '182031-男', '182033-男'},
 {'182039-男', '182040-男', '182041-男', '182042-男'},
 {'183691-女', '183706-女', '183731-女'},
 {'180449-女', '180455-女', '180456-女', '180476-女', '180489-女', '180491-女'},
 {'180624-男', '181013-女', '181042-女'},
 {'182244-女', '182283-女'},
 {'182652-女', '182655-女', '182668-女'},
 {'180841-女', '180844-女', '180858-女'},
 {'180109-女', '180135-女', '180139-女', '180192-女'},
 {'181065-男', '181101-男', '181112-男', '181117-男'},
 {'181266-女', '181271-女', '181302-女', '181303-女'},
 {'183036-男', '183092-男', '183093-男'},
 {'180038-女', '180059-女'},
 {'183237-女', '183247-女', '183252-女', '183254-女'},
 {'183414-女', '183418-女'},
 {'182579-女', '182590-女', '182593-女'},
 {'182010-女', '182012-女', '182464-女'},
 {'184239-女', '184244-女'},
 {'182931-男', '182936-男', '182958-男'},
 {'182422-女', '182500-女'},
 {'180096-女', '181113-男'},
 {'181017-女', '181028-女', '181030-女', '181035-女'},
 {'181255-女', '181260-女', '181282-女', '181305-女'},
 {'181387-男', '181404-男', '181418-男'},
 {'180074-男', '180077-男'},
 {'181652-男', '181657-男', '181667-男', '181670-男', '184107-男'},
 {'182317-女', '182352-女', '182355-女', '182380-女'},
 {'180398-女', '180415-女'},
 {'182432-女', '182485-女', '182527-女'},
 {'181603-男', '181615-男', '181639-男', '181640-男'},
 {'182577-女', '182603-女'},
 {'183452-女', '183461-女', '183464-女'},
 {'180240-女', '180295-女'},
 {'182716-男', '182718-男'},
 {'182453-女', '182455-女', '184207-女', '184224-女'},
 {'181139-男', '181145-男', '181167-男', '184096-男', '184099-男'},
 {'181517-男', '181526-男'},
 {'180590-女', '180591-女', '180603-女'},
 {'180846-女', '180862-女', '180864-女'},
 {'181617-男', '181628-男', '181644-男'},
 {'183019-男', '183040-男'},
 {'183245-女', '183250-女'},
 {'181366-男', '181368-男'},
 {'183305-女', '183308-女', '183317-女'},
 {'183216-男', '183220-男', '183224-男'},
 {'182927-男', '182930-男', '182935-男', '182950-男', '182956-男', '182957-男'},
 {'182156-女', '182695-女'},
 {'182922-男', '182944-男', '182953-男', '182954-男', '182962-男'},
 {'182414-男', '184198-男'},
 {'180715-女', '180740-女'},
 {'182726-男', '182727-男', '182728-男', '184263-男'},
 {'180610-女', '181587-女'},
 {'180722-女', '180730-女'},
 {'182131-女', '182133-女', '182199-女'},
 {'181077-男', '181098-男', '184075-男', '184077-男'},
 {'180555-女', '180558-女'},
 {'180011-女', '180012-女', '180027-女', '180040-女', '180042-女'},
 {'180248-女', '180287-女', '180296-女'},
 {'183457-女', '183482-女'},
 {'181718-女', '181744-女'},
 {'180373-女', '180417-女'},
 {'183836-女', '183865-女'},
 {'183613-男', '183614-男'},
 {'183408-女', '183415-女'},
 {'183785-女', '183794-女', '183808-女', '184339-女'},
 {'180257-女', '180274-女', '180305-女', '180318-女', '180339-女'},
 {'182379-女', '182387-女', '184191-女'},
 {'181068-男', '181359-男', '181362-男'},
 {'183674-女', '183735-女', '183757-女'},
 {'181386-男', '181391-男', '181453-男', '181457-男'},
 {'182729-男', '182733-男', '182735-男'},
 {'181058-男', '181078-男', '181095-男'},
 {'180781-女', '180847-女', '184012-女', '184018-女', '184043-女'},
 {'182046-女', '182051-女', '182055-女'},
 {'183784-女', '183800-女', '183803-女'},
 {'182605-男', '182613-男'},
 {'183670-女', '183744-女', '184324-女'},
 {'181475-女', '181480-女'},
 {'182532-男', '182539-男'},
 {'180642-女', '180681-女', '180688-女'},
 {'180428-男', '180432-男', '180435-男', '180443-男'},
 {'180523-男', '180524-男', '182415-男'},
 {'183058-男', '183096-男'},
 {'181948-女', '181949-女', '181950-女'},
 {'183788-女', '183805-女', '183809-女'},
 {'180544-女', '180554-女', '180572-女', '180589-女'},
 {'180444-女', '180450-女', '180484-女'},
 {'182673-女', '184235-女'},
 {'181760-男', '181768-男', '181790-男', '181792-男'},
 {'181099-男', '181102-男', '181107-男', '184071-男'},
 {'183662-女', '183695-女'},
 {'181154-男', '184086-男', '184093-男'},
 {'181487-男', '181490-男', '181493-男'},
 {'183392-女', '183398-女'},
 {'183410-女', '183416-女'},
 {'180433-男', '180499-女'},
 {'182848-男', '182850-男'},
 {'180146-女', '180191-女'},
 {'181905-男', '181907-男'},
 {'183445-男', '183447-男'},
 {'183310-女', '183321-女'},
 {'182114-女', '182137-女'},
 {'183302-女', '183306-女'},
 {'180381-女', '180401-女', '180420-女'},
 {'181735-女', '181747-女', '184140-女'},
 {'181618-男', '181619-男', '181637-男'},
 {'183386-女', '183409-女'},
 {'180526-男', '180531-男'},
 {'182586-女', '182598-女'},
 {'182373-女', '182383-女'},
 {'180321-女', '183953-女', '183954-女', '183957-女'},
 {'182676-女', '182704-女', '182707-女'},
 {'182578-女', '182581-女'},
 {'182675-女', '182687-女'},
 {'180162-女', '183925-女'},
 {'182612-男', '182614-男', '182615-男'},
 {'180771-女', '180774-女', '180818-女', '180870-女'},
 {'180244-女', '180333-女', '180334-女'},
 {'183178-女', '183182-女', '183196-女'},
 {'181913-男', '181915-男'},
 {'182682-女', '182708-女'},
 {'180145-女', '180166-女'},
 {'182191-女', '182873-男'},
 {'180460-女', '180462-女', '180474-女', '180496-女', '180497-女'},
 {'181516-男', '181545-男'},
 {'182423-女', '182458-女', '182482-女'},
 {'180104-女', '180108-女', '180147-女'},
 {'180031-女', '180045-女', '180071-女'},
 {'181389-男', '181398-男', '181452-男', '181464-男'},
 {'180518-男', '184329-男'},
 {'181558-男', '181561-男', '181562-男'},
 {'182689-女', '182694-女'},
 {'182452-女', '182461-女', '182481-女', '182497-女'},
 {'180352-女', '180357-女', '180403-女'},
 {'183589-女', '183592-女'},
 {'182761-男', '182769-男'},
 {'182371-女', '183797-女'},
 {'181699-男', '181712-女'},
 {'181501-男', '181510-男', '181527-男'},
 {'182460-女', '182465-女', '182478-女'},
 {'180510-女', '183365-女'},
 {'181331-男', '181340-男', '181342-男'},
 {'181337-男', '181354-男'},
 {'183699-女', '183720-女', '183722-女', '183738-女'},
 {'181734-女', '181742-女'},
 {'182683-女', '182699-女'},
 {'180313-女', '181935-女', '181941-女', '181947-女'},
 {'180015-女', '180069-女'},
 {'180772-女', '180788-女'},
 {'182274-女', '183992-女'},
 {'181514-男', '181531-男', '181538-男'},
 {'180527-男', '180794-女', '183949-女', '184044-女'},
 {'182542-男', '182543-男'},
 {'180375-女', '180405-女'},
 {'183141-男', '183142-男', '183162-男'},
 {'180561-女', '180584-女', '180601-女'},
 {'180695-女', '183989-女'},
 {'181883-男', '181895-男', '181899-男', '181906-男', '181912-男', '184302-男'},
 {'182189-女', '182197-女'},
 {'182273-女', '182277-女', '182279-女'},
 {'181861-女', '181867-女'},
 {'181520-男', '181525-男'},
 {'180384-女', '180385-女'},
 {'183550-女', '183608-女'},
 {'182270-女', '182276-女'},
 {'181312-女', '181321-女'},
 {'183353-男', '183355-男'},
 {'181549-男', '181580-男', '181581-男'},
 {'180154-女', '181094-男', '181096-男', '181100-男', '181105-男'},
 {'182172-女', '182174-女'},
 {'180652-女', '180682-女', '181554-男'},
 {'181776-男', '181778-男'},
 {'182766-男'},
 {'180084-女', '180125-女'},
 {'181728-女', '181738-女'},
 {'182348-女', '182811-女', '184189-女'},
 {'181892-男', '181903-男', '181908-男', '181919-男'},
 {'181890-男'},
 {'181841-男', '184014-女'},
 {'182243-女', '182255-女', '184155-女'},
 {'183673-女', '183697-女', '183749-女'},
 {'183382-女', '183389-女'},
 {'182557-女', '182570-女'},
 {'180785-女', '182560-女', '184042-女'},
 {'182375-女', '182376-女'},
 {'181550-男', '181574-男', '181575-男'},
 {'180817-女', '180872-女'},
 {'183065-男', '183128-男', '184305-男'},
 {'180764-男', '180766-男'},
 {'182918-男', '182963-男'},
 {'180142-女', '181889-男'},
 {'182411-男', '184196-男'},
 {'181923-女', '181942-女'},
 {'182917-男', '182941-男', '182952-男'},
 {'183692-女', '183728-女', '183747-女', '183754-女', '184055-女'},
 {'180655-女', '180660-女'},
 {'183612-男', '183629-男'},
 {'181309-女', '181313-女'},
 {'181301-女', '181310-女', '183814-女'},
 {'182337-女', '184181-女'},
 {'180767-女', '180853-女'},
 {'180819-女', '180855-女'},
 {'184026-女'},
 {'182079-女', '182094-女'},
 {'183376-女', '183381-女'},
 {'182628-女', '182630-女', '182679-女', '182680-女', '182713-女'},
 {'182099-男', '182110-男'},
 {'183054-男', '183088-男', '183105-男', '184297-男'},
 {'181021-女', '181036-女'},
 {'182626-女', '184308-男'},
 {'180393-女', '180411-女'},
 {'182447-女', '182498-女', '184215-女'},
 {'180414-女', '180423-女'},
 {'182393-女', '182394-女'},
 {'181011-女', '181047-女', '181050-女'},
 {'180649-女', '183998-女'},
 {'182338-女', '182391-女'},
 {'182592-女', '184229-女'},
 {'180552-女', '180571-女', '180588-女', '180613-女'},
 {'181748-女', '184134-女'},
 {'183397-女', '183417-女'},
 {'183132-女', '183136-女'},
 {'183315-女', '183324-女'},
 {'182583-女', '182597-女'},
 {'181831-男', '182587-女'},
 {'182327-女', '182390-女', '182408-女'},
 {'183799-女', '184336-女'},
 {'182569-女', '182573-女'},
 {'181333-男', '181372-男'},
 {'180213-男', '183187-女', '183193-女'},
 {'182991-男', '182996-男'},
 {'182646-女', '182660-女'},
 {'180810-女', '184040-女'},
 {'181055-男', '181060-男', '181062-男'},
 {'182649-女', '182653-女'},
 {'181524-男'},
 {'182268-女', '182280-女'},
 {'180454-女', '180468-女'},
 {'182165-女', '182170-女'},
 {'180823-女', '184015-女'},
 {'182508-女', '184211-女'},
 {'180255-女', '180282-女'},
 {'183297-女', '183299-女'},
 {'180835-女', '184023-女'},
 {'182089-女', '183076-男'},
 {'183595-女'},
 {'183473-女', '183489-女'},
 {'182757-男', '182775-男', '182781-男'},
 {'181926-女'},
 {'181484-男', '181489-男', '181495-男', '181497-男'},
 {'183300-女', '183325-女'},
 {'183807-女', '183811-女'},
 {'181855-女', '181863-女', '181866-女'},
 {'182356-女', '182370-女'},
 {'181378-男', '181407-男'},
 {'182134-女', '182192-女'},
 {'180814-女', '180867-女'},
 {'182939-男', '182959-男'},
 {'181975-男', '182526-女'},
 {'181690-男', '181693-男'},
 {'182433-女', '182470-女'},
 {'182907-男', '183101-男'},
 {'182741-男', '182754-男'},
 {'180359-女', '180402-女'},
 {'181681-男', '181695-男', '181697-男'},
 {'182501-女', '182524-女'},
 {'181864-女', '181870-女'},
 {'180097-女', '180206-女'},
 {'180480-女', '181629-男'},
 {'180249-女', '180332-女'},
 {'181604-男', '181621-男', '181631-男'},
 {'182505-女'},
 {'183364-女', '183373-女'},
 {'180016-女', '180063-女'},
 {'180611-女', '180612-女'},
 {'181945-女'},
 {'183354-男'},
 {'182657-女', '182672-女'},
 {'182892-女', '182894-女'},
 {'183346-男', '183347-男'},
 {'181803-男', '181807-男'},
 {'182750-男', '182751-男'},
 {'182596-女', '182601-女'},
 {'182269-女', '182285-女'},
 {'181787-男', '181805-男'},
 {'181980-男', '181990-男', '181994-男'},
 {'180369-女', '180416-女'},
 {'181891-男', '181896-男', '181900-男'},
 {'182643-女', '182647-女'},
 {'182984-男', '182998-男'},
 {'180749-女'},
 {'183281-男', '183292-男'},
 {'180778-女', '180865-女'},
 {'181041-女', '183778-女'},
 {'182023-男', '182028-男'},
 {'180325-女', '183967-女'},
 {'180265-女', '180317-女'},
 {'182347-女', '182385-女'},
 {'180797-女', '180843-女'},
 {'180355-女', '180358-女'},
 {'180796-女', '181029-女'},
 {'181563-男', '181566-男'},
 {'184209-女'},
 {'180676-女', '184000-女'},
 {'180241-女', '180242-女'},
 {'182921-男'},
 {'184141-女'},
 {'182888-女', '184280-女', '184282-女'},
 {'182881-女', '182893-女'},
 {'180678-女', '180692-女'},
 {'183708-女'},
 {'181198-女', '181202-女'},
 {'180247-女', '180272-女'},
 {'181442-男'},
 {'183171-男'},
 {'181031-女', '181053-女'},
 {'183061-男', '183091-男'},
 {'180268-女', '180286-女'},
 {'182658-女', '182661-女'},
 {'181683-男', '184109-男'},
 {'182132-女', '182136-女'},
 {'182207-女'},
 {'181630-男'},
 {'182992-男', '183000-男', '183001-男'},
 {'181015-女', '181032-女'},
 {'180734-女', '180748-女'},
 {'182311-女', '182359-女'},
 {'180802-女'},
 {'181774-男', '183898-女'},
 {'180729-女', '180735-女'},
 {'183393-女', '183405-女'},
 {'183394-女', '183395-女'},
 {'182093-女', '182095-女'},
 {'180638-女'},
 {'180246-女'},
 {'181314-女', '183095-男'},
 {'180812-女'},
 {'181961-男'},
 {'180751-男', '180827-女'},
 {'181646-男'},
 {'183782-女', '183802-女'},
 {'180758-男'},
 {'183451-女'},
 {'183073-男', '183078-男'},
 {'183360-女', '183361-女'},
 {'183474-女', '183477-女'},
 {'180314-女'},
 {'180182-女', '183923-女'},
 {'183164-男', '183169-男'},
 {'180112-女'},
 {'181826-男', '181840-男'},
 {'181335-男', '181336-男'},
 {'182254-女', '182261-女'},
 {'184119-男'},
 {'181555-男', '181557-男'},
 {'180123-女', '183930-女'},
 {'183685-女', '183723-女'},
 {'180083-女', '180114-女'},
 {'180717-女', '180731-女'},
 {'183041-男', '184299-男'},
 {'180581-女', '182564-女'},
 {'180320-女', '183546-女'},
 {'182194-女', '182212-女'}]

In [55]:
# 数据格式转换
tuples = [tuple(x) for x in df_3[['校园卡号_x','校园卡号_y']].values]
G = nx.DiGraph()
G.add_edges_from(tuples)

In [56]:
# LPA本身不稳定，因此，社群存在小范围波动
com = list(lpa(G))
print('社区数量',len(com))

社区数量 451

449

In [57]:
# 打印分群数据 仅展示部分数据
for i in com:
    print(i)

{'181268-女', '181293-女'}
{'183665-女', '180399-女'}
{'183979-女', '180363-女', '181876-女', '180364-女'}
{'182138-女', '184188-女', '182213-女', '182392-女', '182350-女', '182622-女', '180167-女', '182180-女', '182049-女', '180111-女', '184238-女', '182377-女'}
{'183424-女', '183422-女', '183420-女', '183419-女'}
{'180742-女', '180726-女'}
{'180792-女', '180849-女', '180822-女'}
{'181929-女', '181951-女', '181928-女'}
{'181203-女', '181184-女', '181201-女'}
{'180728-女', '181263-女', '180747-女', '180714-女'}
{'181848-女', '181865-女', '181871-女'}
{'183582-女', '183603-女', '183579-女'}
{'180091-女', '180208-女', '180094-女', '180203-女', '180131-女'}
{'181343-男', '181338-男', '181344-男', '181350-男'}
{'182300-女', '182278-女'}
{'181273-女', '181318-女', '181316-女'}
{'180360-女', '180394-女', '180377-女', '180085-女', '180342-男', '180171-女', '180412-女', '180189-女', '180382-女'}
{'183009-男', '182980-男', '182976-男', '182978-男'}
{'182865-男', '184277-男', '183097-男'}
{'182196-女', '182210-女', '182200-女', '182201-女'}
{'183260-女', '183243-女'}
{'183690-女', '183641-女', '183688-女'}
{'180615-女', '180547-女', '180578-女', '180545-女'}
{'182320-女', '182332-女', '184179-女', '182378-女', '184184-女'}
{'181650-男', '181661-男', '184104-男'}
{'181379-男', '181381-男', '181448-男', '181383-男'}
{'180793-女', '184028-女', '180783-女'}
{'180711-女', '180732-女', '180738-女', '180712-女'}
{'180173-女', '180102-女', '182345-女', '180113-女', '180169-女', '180193-女'}
{'183644-女', '183647-女'}
{'183343-男', '183980-女', '180383-女'}
{'181066-男', '181103-男', '181091-男', '181069-男', '181073-男'}
{'180551-女', '180593-女', '180609-女', '180587-女', '180614-女'}
{'181136-男', '181571-男', '181582-男', '181133-男', '181552-男'}
{'182340-女', '182329-女', '182239-男', '182403-女', '182304-女'}
{'183768-男', '184333-男', '183772-男'}
{'181664-男', '181658-男', '181656-男'}
{'183671-女', '183742-女', '183719-女', '183881-女', '183851-女', '183737-女', '183713-女', '183850-女', '183732-女', '183734-女', '183701-女', '183853-女', '183726-女'}
{'181564-男', '181568-男', '181556-男', '181559-男'}
{'182333-女', '181191-女'}
{'183314-女', '183307-女', '183303-女'}
{'181543-男', '181498-男', '181506-男', '181536-男', '181505-男'}
{'180197-女', '180159-女', '180165-女', '180137-女', '180136-女'}
{'180477-女', '180505-女', '180504-女', '180467-女', '180506-女', '180448-女', '180486-女'}
{'184024-女', '180800-女', '184034-女', '184036-女'}
{'182810-女', '182821-女', '182807-女', '182813-女', '182819-女'}
{'182551-女', '182555-女', '182565-女'}
{'180122-女', '180133-女'}
{'180780-女', '180851-女', '180856-女', '181461-男'}
{'182474-女', '182459-女'}
{'180493-女', '180459-女', '181176-女', '180500-女', '180457-女'}
{'182361-女', '184190-女'}
{'182878-男', '182866-男'}
{'180644-女', '180666-女', '180690-女', '180672-女'}
{'182517-女', '182475-女', '182427-女'}
{'180464-女', '180482-女', '180511-女', '180466-女', '181847-女', '180445-女'}
{'180087-女', '180095-女', '180202-女', '180144-女', '180098-女'}
{'183999-女', '180665-女', '180651-女'}
{'181408-男', '181443-男'}
{'182703-女', '182705-女', '182677-女'}
{'181921-女', '181952-女', '181943-女'}
{'180683-女', '180694-女', '183997-女'}
{'183859-女', '183854-女', '183872-女', '183712-女', '183852-女', '183709-女', '183739-女', '183753-女'}
{'182120-女', '182115-女', '182130-女', '182205-女'}
{'181142-男', '184098-男', '184100-男'}
{'183798-女', '183787-女'}
{'184298-男', '183074-男', '183123-男', '183107-男'}
{'182758-男', '182788-男', '182764-男', '182783-男', '182759-男'}
{'180048-女', '183901-女', '180026-女', '180055-女'}
{'183202-男', '183234-男'}
{'181325-男', '181346-男', '181355-男'}
{'180309-女', '180293-女', '180328-女'}
{'180705-男', '180704-男'}
{'181507-男', '181500-男', '181509-男', '181508-男', '181530-男', '181503-男'}
{'181515-男', '181534-男'}
{'181034-女', '181026-女', '181016-女'}
{'183640-女', '183642-女'}
{'183847-女', '181626-男', '181597-男', '181623-男'}
{'182983-男', '182999-男', '182986-男', '182987-男'}
{'183338-男', '183344-男', '183341-男', '183345-男', '183330-男'}
{'183599-女', '183569-女', '183583-女'}
{'180262-女', '180820-女'}
{'183469-女', '183468-女', '183488-女'}
{'180252-女', '180316-女', '183952-女'}
{'183675-女', '183743-女', '183661-女', '183711-女'}
{'180198-女', '180164-女', '180105-女', '180118-女'}
{'183401-女', '183385-女'}
{'181529-男', '181364-男', '181528-男'}
{'182031-男', '182029-男', '182033-男', '182016-男'}
{'182042-男', '182039-男', '182041-男', '182040-男'}
{'183731-女', '183691-女', '183706-女'}
{'180456-女', '180489-女', '180491-女', '180476-女', '180449-女', '180455-女'}
{'180624-男', '181013-女', '181042-女'}
{'182283-女', '182244-女'}
{'182655-女', '182668-女', '182652-女'}
{'180844-女', '180858-女', '180841-女'}
{'180139-女', '180135-女', '180109-女', '180192-女'}
{'181101-男', '181112-男', '181065-男', '181117-男'}
{'181302-女', '181271-女', '181266-女', '181303-女'}
{'183093-男', '183092-男', '183036-男'}
{'180038-女', '180059-女'}
{'183247-女', '183237-女', '183254-女', '183252-女'}
{'183418-女', '183414-女'}
{'182590-女', '182579-女', '182593-女'}
{'182464-女', '182012-女', '182010-女'}
{'184244-女', '184239-女'}
{'182958-男', '182936-男', '182931-男'}
{'182500-女', '182422-女'}
{'180096-女', '181113-男'}
{'181017-女', '181035-女', '181030-女', '181028-女'}
{'181282-女', '181305-女', '181260-女', '181255-女'}
{'181404-男', '181418-男', '181387-男'}
{'180077-男', '180074-男'}
{'181667-男', '181657-男', '181670-男', '184107-男', '181652-男'}
{'182352-女', '182380-女', '182317-女', '182355-女'}
{'180398-女', '180415-女'}
{'182432-女', '182527-女', '182485-女'}
{'181615-男', '181640-男', '181639-男', '181603-男'}
{'182603-女', '182577-女'}
{'183452-女', '183461-女', '183464-女'}
{'180295-女', '180240-女'}
{'182716-男', '182718-男'}
{'182453-女', '184207-女', '182455-女', '184224-女'}
{'181145-男', '184099-男', '181167-男', '181139-男', '184096-男'}
{'181526-男', '181517-男'}
{'180591-女', '180603-女', '180590-女'}
{'180862-女', '180846-女', '180864-女'}
{'181628-男', '181617-男', '181644-男'}
{'183019-男', '183040-男'}
{'183245-女', '183250-女'}
{'181368-男', '181366-男'}
{'183305-女', '183317-女', '183308-女'}
{'183220-男', '183224-男', '183216-男'}
{'182930-男', '182927-男', '182935-男', '182957-男', '182956-男', '182950-男'}
{'182156-女', '182695-女'}
{'182953-男', '182954-男', '182922-男', '182962-男', '182944-男'}
{'184198-男', '182414-男'}
{'180740-女', '180715-女'}
{'182727-男', '184263-男', '182728-男', '182726-男'}
{'180610-女', '181587-女'}
{'180730-女', '180722-女'}
{'182133-女', '182199-女', '182131-女'}
{'184077-男', '181098-男', '181077-男', '184075-男'}
{'180555-女', '180558-女'}
{'180042-女', '180027-女', '180012-女', '180040-女', '180011-女'}
{'180287-女', '180248-女', '180296-女'}
{'183482-女', '183457-女'}
{'181718-女', '181744-女'}
{'180373-女', '180417-女'}
{'183865-女', '183836-女'}
{'183613-男', '183614-男'}
{'183408-女', '183415-女'}
{'183808-女', '183785-女', '184339-女', '183794-女'}
{'180274-女', '180305-女', '180339-女', '180257-女', '180318-女'}
{'184191-女', '182387-女', '182379-女'}
{'181362-男', '181068-男', '181359-男'}
{'183674-女', '183735-女', '183757-女'}
{'181391-男', '181453-男', '181457-男', '181386-男'}
{'182729-男', '182735-男', '182733-男'}
{'181095-男', '181058-男', '181078-男'}
{'180781-女', '184012-女', '184018-女', '184043-女', '180847-女'}
{'182055-女', '182051-女', '182046-女'}
{'183800-女', '183784-女', '183803-女'}
{'182613-男', '182605-男'}
{'183670-女', '184324-女', '183744-女'}
{'181480-女', '181475-女'}
{'182532-男', '182539-男'}
{'180681-女', '180642-女', '180688-女'}
{'180432-男', '180428-男', '180443-男', '180435-男'}
{'180523-男', '182415-男', '180524-男'}
{'183096-男', '183058-男'}
{'181950-女', '181949-女', '181948-女'}
{'183805-女', '183809-女', '183788-女'}
{'180554-女', '180589-女', '180572-女', '180544-女'}
{'180444-女', '180484-女', '180450-女'}
{'182673-女', '184235-女'}
{'181760-男', '181792-男', '181768-男', '181790-男'}
{'181102-男', '181107-男', '181099-男', '184071-男'}
{'183662-女', '183695-女'}
{'184086-男', '184093-男', '181154-男'}
{'181487-男', '181490-男', '181493-男'}
{'183398-女', '183392-女'}
{'183416-女', '183410-女'}
{'180499-女', '180433-男'}
{'182848-男', '182850-男'}
{'180191-女', '180146-女'}
{'181905-男', '181907-男'}
{'183447-男', '183445-男'}
{'183321-女', '183310-女'}
{'182137-女', '182114-女'}
{'183306-女', '183302-女'}
{'180420-女', '180381-女', '180401-女'}
{'181747-女', '181735-女', '184140-女'}
{'181619-男', '181637-男', '181618-男'}
{'183386-女', '183409-女'}
{'180526-男', '180531-男'}
{'182598-女', '182586-女'}
{'182383-女', '182373-女'}
{'183953-女', '183954-女', '180321-女', '183957-女'}
{'182676-女', '182707-女', '182704-女'}
{'182581-女', '182578-女'}
{'182675-女', '182687-女'}
{'183925-女', '180162-女'}
{'182615-男', '182614-男', '182612-男'}
{'180870-女', '180774-女', '180818-女', '180771-女'}
{'180333-女', '180334-女', '180244-女'}
{'183178-女', '183182-女', '183196-女'}
{'181915-男', '181913-男'}
{'182682-女', '182708-女'}
{'180145-女', '180166-女'}
{'182191-女', '182873-男'}
{'180496-女', '180462-女', '180497-女', '180460-女', '180474-女'}
{'181516-男', '181545-男'}
{'182482-女', '182458-女', '182423-女'}
{'180108-女', '180147-女', '180104-女'}
{'180071-女', '180031-女', '180045-女'}
{'181398-男', '181464-男', '181452-男', '181389-男'}
{'184329-男', '180518-男'}
{'181561-男', '181562-男', '181558-男'}
{'182689-女', '182694-女'}
{'182461-女', '182497-女', '182452-女', '182481-女'}
{'180357-女', '180352-女', '180403-女'}
{'183592-女', '183589-女'}
{'182769-男', '182761-男'}
{'183797-女', '182371-女'}
{'181699-男', '181712-女'}
{'181510-男', '181501-男', '181527-男'}
{'182465-女', '182460-女', '182478-女'}
{'183365-女', '180510-女'}
{'181342-男', '181331-男', '181340-男'}
{'181354-男', '181337-男'}
{'183699-女', '183738-女', '183720-女', '183722-女'}
{'181734-女', '181742-女'}
{'182683-女', '182699-女'}
{'181935-女', '180313-女', '181947-女', '181941-女'}
{'180069-女', '180015-女'}
{'180788-女', '180772-女'}
{'182274-女', '183992-女'}
{'181538-男', '181514-男', '181531-男'}
{'183949-女', '180527-男', '180794-女', '184044-女'}
{'182542-男', '182543-男'}
{'180375-女', '180405-女'}
{'183142-男', '183141-男', '183162-男'}
{'180584-女', '180601-女', '180561-女'}
{'183989-女', '180695-女'}
{'181912-男', '181883-男', '181895-男', '181899-男', '181906-男', '184302-男'}
{'182189-女', '182197-女'}
{'182273-女', '182279-女', '182277-女'}
{'181861-女', '181867-女'}
{'181525-男', '181520-男'}
{'180385-女', '180384-女'}
{'183608-女', '183550-女'}
{'182270-女', '182276-女'}
{'181312-女', '181321-女'}
{'183353-男', '183355-男'}
{'181549-男', '181580-男', '181581-男'}
{'181105-男', '181100-男', '181096-男', '181094-男', '180154-女'}
{'182172-女', '182174-女'}
{'180682-女', '181554-男', '180652-女'}
{'181776-男', '181778-男'}
{'182766-男'}
{'180084-女', '180125-女'}
{'181728-女', '181738-女'}
{'182348-女', '182811-女', '184189-女'}
{'181892-男', '181908-男', '181919-男', '181903-男'}
{'181890-男'}
{'181841-男', '184014-女'}
{'182255-女', '182243-女', '184155-女'}
{'183673-女', '183697-女', '183749-女'}
{'183382-女', '183389-女'}
{'182570-女', '182557-女'}
{'180785-女', '182560-女', '184042-女'}
{'182375-女', '182376-女'}
{'181550-男', '181575-男', '181574-男'}
{'180817-女', '180872-女'}
{'184305-男', '183128-男', '183065-男'}
{'180764-男', '180766-男'}
{'182963-男', '182918-男'}
{'181889-男', '180142-女'}
{'184196-男', '182411-男'}
{'181923-女', '181942-女'}
{'182952-男', '182941-男', '182917-男'}
{'183692-女', '183728-女', '183754-女', '183747-女', '184055-女'}
{'180655-女', '180660-女'}
{'183629-男', '183612-男'}
{'181313-女', '181309-女'}
{'181301-女', '181310-女', '183814-女'}
{'182337-女', '184181-女'}
{'180853-女', '180767-女'}
{'180855-女', '180819-女'}
{'184026-女'}
{'182094-女', '182079-女'}
{'183376-女', '183381-女'}
{'182679-女', '182680-女', '182628-女', '182713-女', '182630-女'}
{'182110-男', '182099-男'}
{'183105-男', '184297-男', '183088-男', '183054-男'}
{'181036-女', '181021-女'}
{'182626-女', '184308-男'}
{'180411-女', '180393-女'}
{'184215-女', '182447-女', '182498-女'}
{'180423-女', '180414-女'}
{'182394-女', '182393-女'}
{'181047-女', '181050-女', '181011-女'}
{'180649-女', '183998-女'}
{'182338-女', '182391-女'}
{'184229-女', '182592-女'}
{'180588-女', '180613-女', '180571-女', '180552-女'}
{'181748-女', '184134-女'}
{'183417-女', '183397-女'}
{'183136-女', '183132-女'}
{'183315-女', '183324-女'}
{'182597-女', '182583-女'}
{'182587-女', '181831-男'}
{'182327-女', '182408-女', '182390-女'}
{'183799-女', '184336-女'}
{'182569-女', '182573-女'}
{'181333-男', '181372-男'}
{'183193-女', '183187-女', '180213-男'}
{'182996-男', '182991-男'}
{'182646-女', '182660-女'}
{'184040-女', '180810-女'}
{'181060-男', '181062-男', '181055-男'}
{'182653-女', '182649-女'}
{'181524-男'}
{'182280-女', '182268-女'}
{'180468-女', '180454-女'}
{'182165-女', '182170-女'}
{'184015-女', '180823-女'}
{'182508-女', '184211-女'}
{'180282-女', '180255-女'}
{'183299-女', '183297-女'}
{'184023-女', '180835-女'}
{'183076-男', '182089-女'}
{'183595-女'}
{'183473-女', '183489-女'}
{'182775-男', '182757-男', '182781-男'}
{'181926-女'}
{'181497-男', '181489-男', '181484-男', '181495-男'}
{'183300-女', '183325-女'}
{'183811-女', '183807-女'}
{'181855-女', '181866-女', '181863-女'}
{'182370-女', '182356-女'}
{'181378-男', '181407-男'}
{'182134-女', '182192-女'}
{'180814-女', '180867-女'}
{'182939-男', '182959-男'}
{'181975-男', '182526-女'}
{'181690-男', '181693-男'}
{'182433-女', '182470-女'}
{'182907-男', '183101-男'}
{'182741-男', '182754-男'}
{'180402-女', '180359-女'}
{'181695-男', '181697-男', '181681-男'}
{'182501-女', '182524-女'}
{'181870-女', '181864-女'}
{'180097-女', '180206-女'}
{'180480-女', '181629-男'}
{'180332-女', '180249-女'}
{'181621-男', '181631-男', '181604-男'}
{'182505-女'}
{'183364-女', '183373-女'}
{'180016-女', '180063-女'}
{'180612-女', '180611-女'}
{'181945-女'}
{'183354-男'}
{'182657-女', '182672-女'}
{'182894-女', '182892-女'}
{'183346-男', '183347-男'}
{'181803-男', '181807-男'}
{'182751-男', '182750-男'}
{'182596-女', '182601-女'}
{'182269-女', '182285-女'}
{'181787-男', '181805-男'}
{'181994-男', '181990-男', '181980-男'}
{'180416-女', '180369-女'}
{'181896-男', '181891-男', '181900-男'}
{'182647-女', '182643-女'}
{'182998-男', '182984-男'}
{'180749-女'}
{'183281-男', '183292-男'}
{'180778-女', '180865-女'}
{'183778-女', '181041-女'}
{'182023-男', '182028-男'}
{'180325-女', '183967-女'}
{'180265-女', '180317-女'}
{'182385-女', '182347-女'}
{'180843-女', '180797-女'}
{'180358-女', '180355-女'}
{'180796-女', '181029-女'}
{'181563-男', '181566-男'}
{'184209-女'}
{'184000-女', '180676-女'}
{'180242-女', '180241-女'}
{'182921-男'}
{'184141-女'}
{'184282-女', '182888-女', '184280-女'}
{'182893-女', '182881-女'}
{'180678-女', '180692-女'}
{'183708-女'}
{'181202-女', '181198-女'}
{'180272-女', '180247-女'}
{'181442-男'}
{'183171-男'}
{'181031-女', '181053-女'}
{'183061-男', '183091-男'}
{'180268-女', '180286-女'}
{'182661-女', '182658-女'}
{'181683-男', '184109-男'}
{'182132-女', '182136-女'}
{'182207-女'}
{'181630-男'}
{'183001-男', '183000-男', '182992-男'}
{'181015-女', '181032-女'}
{'180734-女', '180748-女'}
{'182311-女', '182359-女'}
{'180802-女'}
{'181774-男', '183898-女'}
{'180729-女', '180735-女'}
{'183405-女', '183393-女'}
{'183395-女', '183394-女'}
{'182095-女', '182093-女'}
{'180638-女'}
{'180246-女'}
{'181314-女', '183095-男'}
{'180812-女'}
{'181961-男'}
{'180827-女', '180751-男'}
{'181646-男'}
{'183782-女', '183802-女'}
{'180758-男'}
{'183451-女'}
{'183078-男', '183073-男'}
{'183361-女', '183360-女'}
{'183477-女', '183474-女'}
{'180314-女'}
{'183923-女', '180182-女'}
{'183164-男', '183169-男'}
{'180112-女'}
{'181840-男', '181826-男'}
{'181336-男', '181335-男'}
{'182261-女', '182254-女'}
{'184119-男'}
{'181557-男', '181555-男'}
{'183930-女', '180123-女'}
{'183685-女', '183723-女'}
{'180114-女', '180083-女'}
{'180717-女', '180731-女'}
{'183041-男', '184299-男'}
{'182564-女', '180581-女'}
{'183546-女', '180320-女'}
{'182194-女', '182212-女'}

In [65]:
# 渣女组合
result = data1[(data1['校园卡号']=='181623-男') | (data1['校园卡号']=='183847-女') | \
      (data1['校园卡号']=='181597-男')]
result

,流水号,校园卡号,校园卡编号,消费时间,消费金额,存储金额,余额,消费次数,消费类型,消费项目编码,消费项目序列号,消费操作编码,操作编码,消费地点,消费时间_F,消费时间_5,Date_5_cnt,性别,tsm
45,116969969,181623-男,20181623,2019-04-01 10:22:00,3.5,0.0,26.52,432,消费,12,NaN,NaN,236,第一食堂,2019-04-01 10:22:00,2019-04-01 10_4,4,男,2019040110(04);2019040110(05)
235,116967455,181597-男,20181597,2019-04-01 11:18:00,8.0,0.0,76.20,975,消费,154,NaN,NaN,254,第四食堂,2019-04-01 11:18:00,2019-04-01 11_4,124,男,2019040111(03);2019040111(04)
241,116967454,183847-女,20183847,2019-04-01 11:18:00,8.0,0.0,72.60,434,消费,154,NaN,NaN,254,第四食堂,2019-04-01 11:18:00,2019-04-01 11_4,124,女,2019040111(03);2019040111(04)
262,116966775,183847-女,20183847,2019-04-01 11:20:00,1.5,0.0,71.10,435,消费,75,NaN,NaN,3,第四食堂,2019-04-01 11:20:00,2019-04-01 11_4,124,女,2019040111(04);2019040111(05)
3798,116966155,181623-男,20181623,2019-04-01 12:46:00,9.0,0.0,17.52,433,消费,70,NaN,NaN,254,第四食堂,2019-04-01 12:46:00,2019-04-01 12_9,87,男,2019040112(09);2019040112(10)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240162,117119153,183847-女,20183847,2019-04-09 07:44:00,2.0,0.0,32.60,480,消费,19,NaN,NaN,235,第一食堂,2019-04-09 07:44:00,2019-04-09 07_9,506,女,2019040907(08);2019040907(09)
240205,117119156,183847-女,20183847,2019-04-09 07:45:00,2.1,0.0,27.50,483,消费,19,NaN,NaN,235,第一食堂,2019-04-09 07:45:00,2019-04-09 07_9,506,女,2019040907(09);2019040907(10)
240209,117120569,183847-女,20183847,2019-04-09 07:45:00,1.5,0.0,26.00,484,消费,49,NaN,NaN,235,第一食堂,2019-04-09 07:45:00,2019-04-09 07_9,506,女,2019040907(09);2019040907(10)
240341,117119775,181623-男,20181623,2019-04-09 07:48:00,2.5,0.0,137.72,453,消费,20,NaN,NaN,235,第一食堂,2019-04-09 07:48:00,2019-04-09 07_10,391,男,2019040907(09);2019040907(10)
240360,117120579,181623-男,20181623,2019-04-09 07:48:00,1.5,0.0,136.22,454,消费,49,NaN,NaN,235,第一食堂,2019-04-09 07:48:00,2019-04-09 07_10,391,男,2019040907(09);2019040907(10)

In [63]:

# 情侣组合
result = data1[(data1['校园卡号']=='181774-男') | (data1['校园卡号']=='183898-女')]
result = result.sort_values(by='消费时间')

# 用户 -时间-地点关系数据
result = df_1[((df_1['校园卡号_x']=='181774-男') & (df_1['校园卡号_y']=='183898-女')) | \
              ((df_1['校园卡号_y']=='181774-男') & (df_1['校园卡号_x']=='183898-女'))]

# 数据整理保存备用
result.to_csv('resualt.csv',index=False,header=True)

In [64]:
result

,校园卡号_x,消费时间_x,消费地点,tsm,校园卡号_y,消费时间_y,diff,date
1686438,181774-男,2019-04-01 07:36:00,第五食堂,2019040107(07),183898-女,2019-04-01 07:35:00,1.0,2019040107
1801104,181774-男,2019-04-01 07:36:00,第五食堂,2019040107(08),183898-女,2019-04-01 07:35:00,1.0,2019040107
2588734,181774-男,2019-04-10 11:54:00,第四食堂,2019041011(10),183898-女,2019-04-10 11:54:00,0.0,2019041011
2591389,183898-女,2019-04-10 11:54:00,第四食堂,2019041011(10),181774-男,2019-04-10 11:54:00,0.0,2019041011
2998175,181774-男,2019-04-10 11:54:00,第四食堂,2019041011(11),183898-女,2019-04-10 11:54:00,0.0,2019041011
...,...,...,...,...,...,...,...,...
43604388,183898-女,2019-04-09 11:43:00,第四食堂,2019040911(09),181774-男,2019-04-09 11:43:00,0.0,2019040911
45598220,183898-女,2019-04-09 07:32:00,第五食堂,2019040907(06),181774-男,2019-04-09 07:32:00,0.0,2019040907
45601650,181774-男,2019-04-09 07:32:00,第五食堂,2019040907(06),183898-女,2019-04-09 07:32:00,0.0,2019040907
45726505,183898-女,2019-04-09 07:32:00,第五食堂,2019040907(07),181774-男,2019-04-09 07:32:00,0.0,2019040907
45730271,181774-男,2019-04-09 07:32:00,第五食堂,2019040907(07),183898-女,2019-04-09 07:32:00,0.0,2019040907